const mongoose = require("mongoose");
const User = require("../models/user"); // Adjust the path as necessary

const users = [
  {
    username: "priya_m",
    email: "priya@domain.com",
    phone: "+919988776655",
    dob: "1990-05-15",
    city: "Mumbai",
    country: "India",
    graduationYear: 2012,
    degree: "MBA",
    department: "Marketing",
    employer: "BrandX",
    jobTitle: "Brand Manager",
    industry: "Marketing",
    experience: 8,
    skills: ["Marketing Strategy", "Campaign Management"],
    projects: ["Campaign X", "Campaign L"],
    achievements: ["Top Brand Manager"],
    linkedin: "https://www.linkedin.com/in/priya",
    github: "https://github.com/priya",
    profilePicture: "https://example.com/images/priya.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 170,
    isStarAlumni: true,
  },

  {
    username: "rahul_123",
    email: "rahul@domain.com",
    phone: "+919876543210",
    dob: "1990-01-15",
    city: "Delhi",
    country: "India",
    graduationYear: 2012,
    degree: "B.Tech",
    department: "Computer Science",
    employer: "TechCorp",
    jobTitle: "Software Engineer",
    industry: "IT",
    experience: 5,
    skills: ["JavaScript", "Node.js", "MongoDB"],
    projects: ["Project A", "Project B"],
    achievements: ["Employee of the Month"],
    linkedin: "https://www.linkedin.com/in/rahul",
    github: "https://github.com/rahul",
    profilePicture: "https://example.com/images/rahul.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 100,
    isStarAlumni: false,
  },
  {
    username: "anjali_s",
    email: "anjali@domain.com",
    phone: "+919988776655",
    dob: "1988-05-22",
    city: "Mumbai",
    country: "India",
    graduationYear: 2010,
    degree: "M.Sc",
    department: "Data Science",
    employer: "DataSolutions",
    jobTitle: "Data Scientist",
    industry: "Analytics",
    experience: 7,
    skills: ["Python", "R", "Machine Learning"],
    projects: ["Project X", "Project Y"],
    achievements: ["Published Paper in Data Science Journal"],
    linkedin: "https://www.linkedin.com/in/anjali",
    github: "https://github.com/anjali",
    profilePicture: "https://example.com/images/anjali.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 150,
    isStarAlumni: true,
  },
  {
    username: "vikram_patel",
    email: "vikram@domain.com",
    phone: "+917007007007",
    dob: "1992-10-30",
    city: "Ahmedabad",
    country: "India",
    graduationYear: 2014,
    degree: "MBA",
    department: "Marketing",
    employer: "MarketInc",
    jobTitle: "Marketing Manager",
    industry: "Marketing",
    experience: 6,
    skills: ["SEO", "Digital Marketing", "Content Strategy"],
    projects: ["Campaign A", "Campaign B"],
    achievements: ["Top Marketer of the Year"],
    linkedin: "https://www.linkedin.com/in/vikram",
    github: "https://github.com/vikram",
    profilePicture: "https://example.com/images/vikram.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 200,
    isStarAlumni: false,
  },
  {
    username: "neha_jain",
    email: "neha@domain.com",
    phone: "+918855446688",
    dob: "1985-12-05",
    city: "Bangalore",
    country: "India",
    graduationYear: 2007,
    degree: "B.Com",
    department: "Finance",
    employer: "FinCorp",
    jobTitle: "Finance Analyst",
    industry: "Finance",
    experience: 12,
    skills: ["Financial Analysis", "Budgeting", "Forecasting"],
    projects: ["Financial Report A", "Budget Plan B"],
    achievements: ["Certified Financial Analyst"],
    linkedin: "https://www.linkedin.com/in/neha",
    github: "https://github.com/neha",
    profilePicture: "https://example.com/images/neha.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 250,
    isStarAlumni: true,
  },
  {
    username: "sandeep_rao",
    email: "sandeep@domain.com",
    phone: "+919876543210",
    dob: "1993-09-14",
    city: "Hyderabad",
    country: "India",
    graduationYear: 2015,
    degree: "B.Tech",
    department: "Electrical Engineering",
    employer: "ElectroTech",
    jobTitle: "Electrical Engineer",
    industry: "Engineering",
    experience: 4,
    skills: ["Circuit Design", "Power Systems", "PLC Programming"],
    projects: ["Project E", "Project F"],
    achievements: ["Best Engineer Award"],
    linkedin: "https://www.linkedin.com/in/sandeep",
    github: "https://github.com/sandeep",
    profilePicture: "https://example.com/images/sandeep.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 180,
    isStarAlumni: false,
  },
  {
    username: "ananya_g",
    email: "ananya@domain.com",
    phone: "+919900334455",
    dob: "1995-02-20",
    city: "Chennai",
    country: "India",
    graduationYear: 2017,
    degree: "M.Tech",
    department: "Software Engineering",
    employer: "CodeWorks",
    jobTitle: "Software Developer",
    industry: "IT",
    experience: 3,
    skills: ["Java", "C++", "Database Management"],
    projects: ["Project G", "Project H"],
    achievements: ["Young Innovator Award"],
    linkedin: "https://www.linkedin.com/in/ananya",
    github: "https://github.com/ananya",
    profilePicture: "https://example.com/images/ananya.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 130,
    isStarAlumni: true,
  },
  {
    username: "arjun_n",
    email: "arjun@domain.com",
    phone: "+919900112233",
    dob: "1987-08-12",
    city: "Pune",
    country: "India",
    graduationYear: 2009,
    degree: "MBA",
    department: "Operations",
    employer: "OpsInc",
    jobTitle: "Operations Manager",
    industry: "Operations",
    experience: 10,
    skills: ["Logistics", "Supply Chain", "Project Management"],
    projects: ["Project I", "Project J"],
    achievements: ["Best Manager Award"],
    linkedin: "https://www.linkedin.com/in/arjun",
    github: "https://github.com/arjun",
    profilePicture: "https://example.com/images/arjun.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 160,
    isStarAlumni: false,
  },
  {
    username: "priya_agarwal",
    email: "priya@domain.com",
    phone: "+917600300200",
    dob: "1991-11-05",
    city: "Kolkata",
    country: "India",
    graduationYear: 2013,
    degree: "BBA",
    department: "Marketing",
    employer: "MarketGenius",
    jobTitle: "Brand Manager",
    industry: "Marketing",
    experience: 6,
    skills: ["Brand Strategy", "Market Research", "Consumer Behavior"],
    projects: ["Campaign K", "Campaign L"],
    achievements: ["Top Brand Manager"],
    linkedin: "https://www.linkedin.com/in/priya",
    github: "https://github.com/priya",
    profilePicture: "https://example.com/images/priya.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 170,
    isStarAlumni: true,
  },
  {
    username: "vikas_kumar",
    email: "vikas@domain.com",
    phone: "+918823334455",
    dob: "1994-07-25",
    city: "Noida",
    country: "India",
    graduationYear: 2016,
    degree: "MCA",
    department: "Software Development",
    employer: "TechWorld",
    jobTitle: "Full Stack Developer",
    industry: "IT",
    experience: 5,
    skills: ["React", "Node.js", "MongoDB"],
    projects: ["Project M", "Project N"],
    achievements: ["Top Developer Award"],
    linkedin: "https://www.linkedin.com/in/vikas",
    github: "https://github.com/vikas",
    profilePicture: "https://example.com/images/vikas.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 140,
    isStarAlumni: false,
  },
  {
    username: "sonal_mehta",
    email: "sonal@domain.com",
    phone: "+919998877665",
    dob: "1989-03-18",
    city: "Chandigarh",
    country: "India",
    graduationYear: 2011,
    degree: "B.Des",
    department: "Design",
    employer: "DesignWorks",
    jobTitle: "Graphic Designer",
    industry: "Design",
    experience: 8,
    skills: ["Photoshop", "Illustrator", "UI/UX Design"],
    projects: ["Design O", "Design P"],
    achievements: ["Best Designer Award"],
    linkedin: "https://www.linkedin.com/in/sonal",
    github: "https://github.com/sonal",
    profilePicture: "https://example.com/images/sonal.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 200,
    isStarAlumni: false,
  },
  {
    username: "divya_s",
    email: "divya@domain.com",
    phone: "+918877665544",
    dob: "1992-06-30",
    city: "Jaipur",
    country: "India",
    graduationYear: 2014,
    degree: "MBA",
    department: "HR",
    employer: "PeopleInc",
    jobTitle: "HR Manager",
    industry: "Human Resources",
    experience: 6,
    skills: ["Talent Acquisition", "Employee Relations", "Training"],
    projects: ["Project Q", "Project R"],
    achievements: ["Best HR Manager"],
    linkedin: "https://www.linkedin.com/in/divya",
    github: "https://github.com/divya",
    profilePicture: "https://example.com/images/divya.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 190,
    isStarAlumni: true,
  },
  {
    username: "manoj_b",
    email: "manoj@domain.com",
    phone: "+919900223344",
    dob: "1984-12-10",
    city: "Surat",
    country: "India",
    graduationYear: 2006,
    degree: "B.Tech",
    department: "Civil Engineering",
    employer: "BuildIt",
    jobTitle: "Civil Engineer",
    industry: "Construction",
    experience: 15,
    skills: ["Structural Engineering", "Project Management", "AutoCAD"],
    projects: ["Project S", "Project T"],
    achievements: ["Top Engineer Award"],
    linkedin: "https://www.linkedin.com/in/manoj",
    github: "https://github.com/manoj",
    profilePicture: "https://example.com/images/manoj.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 220,
    isStarAlumni: false,
  },
  {
    username: "karan_k",
    email: "karan@domain.com",
    phone: "+919800445566",
    dob: "1990-04-25",
    city: "Kanpur",
    country: "India",
    graduationYear: 2012,
    degree: "M.Tech",
    department: "Computer Engineering",
    employer: "InnovateTech",
    jobTitle: "Machine Learning Engineer",
    industry: "AI",
    experience: 6,
    skills: ["Machine Learning", "Deep Learning", "TensorFlow"],
    projects: ["Project U", "Project V"],
    achievements: ["Top ML Engineer"],
    linkedin: "https://www.linkedin.com/in/karan",
    github: "https://github.com/karan",
    profilePicture: "https://example.com/images/karan.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 210,
    isStarAlumni: true,
  },
  {
    username: "shruti_m",
    email: "shruti@domain.com",
    phone: "+919988665544",
    dob: "1993-07-09",
    city: "Nagpur",
    country: "India",
    graduationYear: 2015,
    degree: "B.Sc",
    department: "Biotechnology",
    employer: "BioTech",
    jobTitle: "Biotech Researcher",
    industry: "Biotechnology",
    experience: 5,
    skills: ["Genomics", "Molecular Biology", "Bioinformatics"],
    projects: ["Project W", "Project X"],
    achievements: ["Top Researcher Award"],
    linkedin: "https://www.linkedin.com/in/shruti",
    github: "https://github.com/shruti",
    profilePicture: "https://example.com/images/shruti.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 160,
    isStarAlumni: false,
  },
  {
    username: "rajesh_k",
    email: "rajesh@domain.com",
    phone: "+919822334455",
    dob: "1986-11-25",
    city: "Indore",
    country: "India",
    graduationYear: 2008,
    degree: "BCA",
    department: "Information Technology",
    employer: "IT Solutions",
    jobTitle: "Network Engineer",
    industry: "IT",
    experience: 12,
    skills: ["Networking", "Cybersecurity", "System Administration"],
    projects: ["Project Y", "Project Z"],
    achievements: ["Best Network Engineer"],
    linkedin: "https://www.linkedin.com/in/rajesh",
    github: "https://github.com/rajesh",
    profilePicture: "https://example.com/images/rajesh.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 180,
    isStarAlumni: true,
  },
  {
    username: "neeraj_d",
    email: "neeraj@domain.com",
    phone: "+919844556677",
    dob: "1994-05-19",
    city: "Gurgaon",
    country: "India",
    graduationYear: 2016,
    degree: "B.Tech",
    department: "Mechanical Engineering",
    employer: "MechTech",
    jobTitle: "Mechanical Engineer",
    industry: "Engineering",
    experience: 5,
    skills: ["Thermodynamics", "Fluid Mechanics", "AutoCAD"],
    projects: ["Project A1", "Project B1"],
    achievements: ["Top Mechanical Engineer"],
    linkedin: "https://www.linkedin.com/in/neeraj",
    github: "https://github.com/neeraj",
    profilePicture: "https://example.com/images/neeraj.jpg",
    connections: [],
    groupJoined: [],
    quizParticipated: [],
    donations: [],
    jobPosts: [],
    listingPosts: [],
    eventsOrganised: [],
    eventsJoined: [],
    points: 170,
    isStarAlumni: false,
  },
];

async function seedUsers() {
  try {
    await User.deleteMany({});
    await User.insertMany(users);
    console.log("Users seeded successfully");
  } catch (error) {
    console.error("Error seeding users:", error);
  }
}

module.exports=seedUsers;
